apiVersion: v1
kind: Plugin
metadata:
  author: xiaowang
  name: Langbot-QQGroup-Add-One-message
  repository: 'https://github.com/1dabai/Langbot-QQGroup-Add-One-message'
  version: 0.1.1
  description:
    en_US: 这是一个qq群聊多人发送同一个消息后触发ai自动回复一样的工具（不兼容QQ官方机器人api）
    zh_Hans: 这是一个qq群聊多人发送同一个消息后触发ai自动回复一样的工具（不兼容QQ官方机器人api）
    th_TH: 这是一个qq群聊多人发送同一个消息后触发ai自动回复一样的工具（不兼容QQ官方机器人api）
    vi_VN: 这是一个qq群聊多人发送同一个消息后触发ai自动回复一样的工具（不兼容QQ官方机器人api）
    es_ES: 这是一个qq群聊多人发送同一个消息后触发ai自动回复一样的工具（不兼容QQ官方机器人api）
  label:
    en_US: Langbot QQGroup Add One message
    zh_Hans: Langbot QQGroup Add One message
    th_TH: Langbot QQGroup Add One message
    vi_VN: Langbot QQGroup Add One message
    es_ES: Langbot QQGroup Add One message
  icon: assets/icon.svg
spec:
  config: []
  components:
    EventListener:
      fromDirs:
      - path: components/event_listener/
execution:
  python:
    path: main.py
    attr: LangbotQQGroupAddOnemessage
