# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import logging
import time
import asyncio
from typing import Optional

from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities import events, context
from langbot_plugin.api.entities.builtin.platform import message as platform_message

logger = logging.getLogger(__name__)

# 触发冷却时间（秒）
TRIGGER_COOLDOWN_TIME = 5 * 60  # 5分钟


class DefaultEventListener(EventListener):

    async def initialize(self):
        await super().initialize()

        # 每个群最近一条消息: {group_id: {"sender_id": str, "text": str, "timestamp": float}}
        self._last_message: dict[str, dict] = {}

        # 每个群已触发的消息冷却记录: {group_id: {text: trigger_timestamp}}
        self._triggered_messages: dict[str, dict[str, float]] = {}

        # 机器人自己的账号ID（用于排除机器人消息）
        self._bot_id: Optional[str] = None

        logger.info("复读插件事件监听器已初始化")

        @self.handler(events.GroupMessageReceived)
        async def on_group_message(event_context: context.EventContext):
            # 立即将处理逻辑放到后台任务，不阻塞流水线
            asyncio.create_task(self._handle_group_message(event_context))

    async def _handle_group_message(self, event_context: context.EventContext):
        """后台处理群消息，不阻塞流水线"""
        try:
            event: events.GroupMessageReceived = event_context.event
            group_id = str(event.launcher_id)
            sender_id = str(event.sender_id)

            # 获取机器人账号ID（仅第一次）
            if self._bot_id is None:
                try:
                    bot_uuid = await event_context.get_bot_uuid()
                    bot_info = await self.plugin.get_bot_info(bot_uuid)
                    if "adapter_runtime_values" in bot_info and "bot_account_id" in bot_info["adapter_runtime_values"]:
                        self._bot_id = str(bot_info["adapter_runtime_values"]["bot_account_id"])
                        logger.info(f"机器人账号ID: {self._bot_id}")
                except Exception as e:
                    logger.warning(f"获取机器人账号ID失败: {e}")

            # 排除机器人自己发送的消息
            if self._bot_id and sender_id == self._bot_id:
                return

            # 从消息链中提取纯文本
            text = ""
            if event.message_chain:
                for component in event.message_chain:
                    if isinstance(component, platform_message.Plain):
                        text += component.text

            # 去除首尾空白，忽略空消息
            text = text.strip()
            if not text:
                return

            current_time = time.time()

            # 清理过期的触发冷却记录
            self._cleanup_expired_triggers(group_id, current_time)

            # 检查该消息是否在冷却期内
            if group_id in self._triggered_messages and text in self._triggered_messages[group_id]:
                self._last_message[group_id] = {
                    "sender_id": sender_id,
                    "text": text,
                    "timestamp": current_time,
                }
                return

            # 只和上一条消息比较（紧跟着的消息）
            last = self._last_message.get(group_id)

            if (last is not None
                    and last["text"] == text
                    and last["sender_id"] != sender_id):
                # 紧跟着的上一条消息内容相同且发送者不同，触发复读
                logger.info(f"检测到连续重复消息，复读: {text}")

                reply_chain = platform_message.MessageChain([
                    platform_message.Plain(text=text),
                ])

                await event_context.reply(reply_chain)

                # 记录触发时间，进入冷却期
                if group_id not in self._triggered_messages:
                    self._triggered_messages[group_id] = {}
                self._triggered_messages[group_id][text] = current_time

                # 清除最近消息记录
                self._last_message.pop(group_id, None)
            else:
                self._last_message[group_id] = {
                    "sender_id": sender_id,
                    "text": text,
                    "timestamp": current_time,
                }

        except Exception as e:
            logger.error(f"处理消息时出错: {e}")

    def _cleanup_expired_triggers(self, group_id: str, current_time: float):
        """清理过期的触发冷却记录"""
        if group_id not in self._triggered_messages:
            return

        self._triggered_messages[group_id] = {
            text: ts for text, ts in self._triggered_messages[group_id].items()
            if current_time - ts < TRIGGER_COOLDOWN_TIME
        }
