# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import logging
import time

from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities import events, context
from langbot_plugin.api.entities.builtin.platform import message as platform_message

logger = logging.getLogger(__name__)

# 消息记录过期时间（秒）
MESSAGE_EXPIRE_TIME = 60  # 1分钟
# 触发冷却时间（秒）
TRIGGER_COOLDOWN_TIME = 5 * 60  # 5分钟


class DefaultEventListener(EventListener):

    async def initialize(self):
        await super().initialize()

        # 每个群只记录最近一条消息: {group_id: {"sender_id": str, "text": str, "time": float}}
        self._last_message: dict[str, dict] = {}

        # 冷却记录: {group_id: {"text": str, "trigger_time": float}}
        self._cooldown: dict[str, dict] = {}

        logger.info("复读插件已初始化")

        @self.handler(events.GroupMessageReceived)
        async def on_group_message(event_context: context.EventContext):
            await self._handle_message(event_context)

    async def _handle_message(self, event_context: context.EventContext):
        """处理群消息"""
        try:
            event: events.GroupMessageReceived = event_context.event
            group_id = str(event.launcher_id)
            sender_id = str(event.sender_id)
            current_time = time.time()

            # 提取纯文本
            text = ""
            has_at = False
            has_quote = False
            has_non_text = False

            if event.message_chain:
                for component in event.message_chain:
                    if isinstance(component, platform_message.Plain):
                        text += component.text
                    elif isinstance(component, platform_message.At):
                        has_at = True
                    elif isinstance(component, platform_message.Quote):
                        has_quote = True
                    elif not isinstance(component, platform_message.Source):
                        has_non_text = True

            text = text.strip()

            # 如果有 @ 或回复，忽略
            if has_at or has_quote:
                return

            # 如果有非文本内容（图片/表情包等），清除记录并忽略
            if has_non_text:
                self._last_message.pop(group_id, None)
                return

            # 没有文本内容，忽略
            if not text:
                return

            # 清理过期记录
            self._cleanup_expired(group_id, current_time)

            # 检查是否在冷却期
            cooldown = self._cooldown.get(group_id)
            if cooldown and cooldown["text"] == text:
                self._last_message[group_id] = {
                    "sender_id": sender_id,
                    "text": text,
                    "time": current_time,
                }
                return

            # 检查是否触发复读
            last = self._last_message.get(group_id)
            if (last is not None
                    and last["text"] == text
                    and last["sender_id"] != sender_id):
                logger.info(f"复读: {text}")

                await event_context.reply(
                    platform_message.MessageChain([
                        platform_message.Plain(text=text),
                    ])
                )

                # 记录冷却
                self._cooldown[group_id] = {
                    "text": text,
                    "trigger_time": current_time,
                }

                # 清除消息记录
                self._last_message.pop(group_id, None)
            else:
                self._last_message[group_id] = {
                    "sender_id": sender_id,
                    "text": text,
                    "time": current_time,
                }

        except Exception as e:
            logger.error(f"处理消息出错: {e}")

    def _cleanup_expired(self, group_id: str, current_time: float):
        """清理过期记录"""
        last = self._last_message.get(group_id)
        if last and (current_time - last["time"] > MESSAGE_EXPIRE_TIME):
            self._last_message.pop(group_id, None)

        cooldown = self._cooldown.get(group_id)
        if cooldown and (current_time - cooldown["trigger_time"] > TRIGGER_COOLDOWN_TIME):
            self._cooldown.pop(group_id, None)
